### ISSUE TITLE
Doesn't work from es-ES to it-IT

### ISSUE THREAD

**Issue by Rvnd0m** [robisim74/gpt-translate-json#1]
Hi Robin,

I'm trying to run the script to translate from spanish to italian, but it gives to me this error:

---------------------------------

gpt-translate-json@0.1.0 gpt-translate-json
gpt-translate-json --apiKey=myapikey --model=gpt-3.5-turbo --maxTokens=3500 --langs=it-IT --originalLang=es-ES

GPT Translate Json
translating files...
file:///C:/Users/myuserfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:152
      throw new Error("Original asset not found");
            ^
Error: Original asset not found
    at C (file:///C:/Users/myuserfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:152:13)
    at et (file:///C:/Users/myuserfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:176:31)

---------------------------------

The current code line on package.json is:

`"gpt-translate-json": "gpt-translate-json --apiKey=myapikey --model=gpt-3.5-turbo --maxTokens=3500 --langs=it-IT --originalLang=es-ES"  },`

And finally, in i18n folder, I have created the es-ES subfolder, so there are two: en-US (already there) and the new one, es-ES, with this app.json file inside:

`{
  "app": {
    "dates": "Fechas y tiempo relativo",
    "devs": {
      "one": "{{ value }} desarrollador de software",
      "other": "{{ value }} desarrolladores de software"
    },
    "greeting": "¡Hola! Soy {{name}}",
    "list": [
      {
        "value": "Primer punto"
      },
      {
        "value": "Segundo punto"
      }
    ],
    "title": "<h1>Biblioteca para traducir JSON usando GPT</h1>"
  }
}`

Do you know what is wrong??

Thanks for your time,

**Comment by Rvnd0m** [comment]
Hi Robins, thank you for your reply.

With that modification it works perfectly on the sample file, but now I'm getting other errors on another json larger file. The large file I want to translate is a one-line 43.000 characters, and already named app.json (I have replaced it and deleted the it-IT other one generated with the sample app.json, just to avoid replacement problems).

This is what I get:

GPT Translate Json
translating files...
Error: app.json: OpenAI API - Bad Request
    at L (file:///C:/Users/userfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:133:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async b (file:///C:/Users/userfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:140:15)
    at async Promise.all (index 0)
    at async C (file:///C:/Users/userfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:150:7)
    at async et (file:///C:/Users/userfolder/Documents/GitHub/gpt-translate-json/node_modules/gpt-translate-json/lib/index.js:176:25)
i18n\.metadata\translated.json
i18n\.metadata\translated-langs.json
Total tokens: 0

**Comment by robisim74** [comment]
Could you post the command you are using (without apiKey)?

Try reducing `maxTokens`. As in doc: `the command splits the files into multiple requests to respect the maximum number of tokens in each request based on the English language`, but you are using ES

**Comment by Rvnd0m** [comment]
Hi Robin, thank you again for your help.

I've changed the max characters from 3500 to 3000. After that, I've run again the command to reinstall

`npm install gpt-translate-json`

and then, the command to run it:

`npm run gpt-translate-json`

Here is an screenshot with the full process, in case you want to see it: https://prnt.sc/KcWn5bpHFr3I

And the tree /f result for the "i18n" folder is:


├───.metadata
│       translated-langs.json
│       translated.json
│
├───en-US
│       app.json
│
└───es-ES
        app.json

**Comment by robisim74** [comment]
Usually the error Bad Request happens when you exceed the limit of character allowed by the API: see for example this thread: https://community.openai.com/t/error-retrieving-completions-400-bad-request/34004

You should try to still reduce the value of `-maxToken` (for example to 1000) and try again.

But be careful: a 43000 character file is split into multiple requests to respect the token limit. If you are using OpenAI's free plan, you would still exceed the 3 RPM limit.

Alternatively you should debug here, and see if the error offers finer details: https://github.com/robisim74/gpt-translate-json/blob/main/src/index.ts#L205

**Comment by robisim74** [comment]
Closing due to lack of feedback
