### ISSUE TITLE
Error when using 4o but works with 4?

### ISSUE THREAD

**Issue by raphaelarias** [robisim74/gpt-translate-json#5]
I encounter this error when I try to use 4o but GPT-4 works fine (version 0.2.2).

Command:
```
gpt-translate-json --model=gpt-4o --maxTokens=1000 --langs=en-US,pt-BR,es-ES,it,fr-FR --originalLang=en-US --basePath=. --assetsPath=config/locales --rules=\"do not translate proper names\",\"do not translate texts enclosed in double braces {{}}\",\"do not translate html tags\",\"do not translate URLs\",\"do not translate texts enclosed in single quotes\",\"do not translate 'icon-'\"
```

```
Error: app.json: OpenAI API - Unexpected token ` in JSON at position 0
    at R (file:///Users/raphaelarias/dev/dashboard/node_modules/gpt-translate-json/lib/index.js:146:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm not sure why, would you know? I assume the response is not expected to have a ` ```json` in the beginning?

**Comment by robisim74** [comment]
Hi Raphael,

thanks for reporting. New GPT model, new behavior... now it returns json md markers in the response: https://community.openai.com/t/json-returning-with-json/584818

I fixed this behavior by changing the prompt in the latest version v0.2.3 and it should now work.

Greetings

**Comment by raphaelarias** [comment]
Thank you! Worked perfectly!
